require('dotenv').config();
const { Sequelize } = require('sequelize');

const dbUser = process.env.DB_USER || 'system';
const dbPassword = process.env.DB_PASSWORD || 'admin123';
const dbHost = process.env.DB_HOST || 'localhost';
const dbPort = process.env.DB_PORT || 1521;
const dbService = process.env.DB_SERVICE_NAME || 'XEPDB1';
const dbWalletPath = process.env.DB_WALLET_PATH;
const dbWalletPassword = process.env.DB_WALLET_PASSWORD;

const dialectOptions = {};

if (dbWalletPath) {
  dialectOptions.connectString = dbService;
  dialectOptions.configDir = dbWalletPath;
  dialectOptions.walletLocation = dbWalletPath;
  if (dbWalletPassword) {
    dialectOptions.walletPassword = dbWalletPassword;
  }
} else {
  if (dbService.trim().startsWith('(')) {
    dialectOptions.connectString = dbService;
  } else {
    dialectOptions.connectString = `${dbHost}:${dbPort}/${dbService}`;
  }
}

const sequelize = new Sequelize({
  dialect: 'oracle',
  username: dbUser,
  password: dbPassword,
  dialectOptions,
  logging: false
});

(async () => {
  try {
    await sequelize.authenticate();
    const queries = [
      'ALTER TABLE "products" ADD "reservedQuantity" NUMBER(10) DEFAULT 0',
      'ALTER TABLE "products" ADD "lowStockThreshold" NUMBER(10) DEFAULT 5',
      'ALTER TABLE "products" ADD "images" CLOB',
      'ALTER TABLE "products" ADD "videoUrls" CLOB',
      'ALTER TABLE "products" ADD "masterCategory" VARCHAR2(255) DEFAULT \'Traditional\'',
      'ALTER TABLE "products" ADD "subCategory" VARCHAR2(255) DEFAULT \'\'',
      'ALTER TABLE "products" ADD "occasion" VARCHAR2(255) DEFAULT \'\'',
      'ALTER TABLE "products" ADD "tags" CLOB',
      'ALTER TABLE "products" ADD "customization" CLOB',
      'ALTER TABLE "products" ADD "shipping" CLOB',
      'ALTER TABLE "products" ADD "rating" NUMBER(3,2) DEFAULT 4.5',
      'ALTER TABLE "products" ADD "details" CLOB',
      'ALTER TABLE "products" ADD "customGiftTagEnabled" NUMBER(1) DEFAULT 1',
      'ALTER TABLE "products" ADD "addonsEnabled" NUMBER(1) DEFAULT 1',
      'ALTER TABLE "products" ADD "customizationText" CLOB',
      'ALTER TABLE "products" ADD "deliveryInfoText" CLOB',
      'ALTER TABLE "products" ADD "isFeatured" NUMBER(1) DEFAULT 0',
      'ALTER TABLE "products" ADD "views" NUMBER(10) DEFAULT 0',
      'ALTER TABLE "products" ADD "clicks" NUMBER(10) DEFAULT 0',
      'ALTER TABLE "orders" ADD "history" CLOB',
      'ALTER TABLE "orders" ADD "internalNotes" CLOB',
      'ALTER TABLE "orders" ADD "source" VARCHAR2(255) DEFAULT \'Website\'',
      'ALTER TABLE "orders" ADD "paymentStatus" VARCHAR2(255) DEFAULT \'Pending\'',
      'ALTER TABLE "orders" ADD "paymentMethod" VARCHAR2(255) DEFAULT \'\'',
      'ALTER TABLE "orders" ADD "advancePaid" NUMBER(10) DEFAULT 0',
      'ALTER TABLE "inquiries" ADD "leadNotes" CLOB',
      'ALTER TABLE "inquiries" ADD "assignedAdmin" VARCHAR2(255) DEFAULT \'Unassigned\'',
      'ALTER TABLE "inquiries" ADD "history" CLOB',
      'ALTER TABLE "inquiries" ADD "budget" VARCHAR2(255) DEFAULT \'\'',
      'ALTER TABLE "inquiries" ADD "quantity" NUMBER(10) DEFAULT 10',
      'ALTER TABLE "inquiries" ADD "subject" VARCHAR2(255) DEFAULT \'Custom Gifting Inquiry\'',
      'ALTER TABLE "settings" MODIFY "value" NULL',
      'CREATE TABLE "testimonials" ("id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR2(255) NOT NULL, "quote" CLOB NOT NULL, "rating" NUMBER(2) DEFAULT 5, "event" VARCHAR2(255) DEFAULT \'\', "isActive" CHAR(1) DEFAULT \'1\', "createdAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL)',
      'CREATE TABLE "categories" ("id" VARCHAR2(255) PRIMARY KEY, "name" VARCHAR2(255) NOT NULL, "parentId" VARCHAR2(255) NULL, "sortOrder" NUMBER(10) DEFAULT 0, "createdAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL)',
      'CREATE TABLE "audit_logs" ("id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "adminUser" VARCHAR2(255) NOT NULL, "action" VARCHAR2(255) NOT NULL, "entity" VARCHAR2(255) NOT NULL, "entityId" VARCHAR2(255) NULL, "details" CLOB NULL, "ipAddress" VARCHAR2(255) NULL, "createdAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL)',
      'CREATE TABLE "hero_banners" ("id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "title" VARCHAR2(255) DEFAULT \'Main Homepage Hero\', "mainImage" CLOB NULL, "floatingImageTop" CLOB NULL, "floatingImageBottom" CLOB NULL, "isActive" CHAR(1) DEFAULT \'1\', "createdAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL)',
      'CREATE TABLE "gallery_items" ("id" VARCHAR2(255) PRIMARY KEY, "title" VARCHAR2(255) DEFAULT \'\', "image" CLOB NOT NULL, "category" VARCHAR2(255) NOT NULL, "description" CLOB DEFAULT \'\', "fileSize" VARCHAR2(255) DEFAULT \'Unknown\', "dimensions" VARCHAR2(255) DEFAULT \'Unknown\', "mediaType" VARCHAR2(255) DEFAULT \'Image\', "width" NUMBER(10) DEFAULT 0, "height" NUMBER(10) DEFAULT 0, "isActive" CHAR(1) DEFAULT \'1\', "createdAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL)',
      // Product columns added in later sessions
      'ALTER TABLE "products" ADD "shortDescription" CLOB',
      'ALTER TABLE "products" ADD "originalPrice" NUMBER(10) DEFAULT 0',
      'ALTER TABLE "products" ADD "sku" VARCHAR2(255)',
      'ALTER TABLE "products" ADD "isActive" NUMBER(1) DEFAULT 1',
      // User columns added for RBAC
      'ALTER TABLE "users" ADD "isActive" NUMBER(1) DEFAULT 1',
      'ALTER TABLE "users" ADD "permissions" CLOB'
    ];
    for (let q of queries) {
      try {
        await sequelize.query(q);
        console.log('Success:', q);
      } catch (e) {
        if (e.message.includes('ORA-01430') || e.message.includes('ORA-00942') || e.message.includes('ORA-00955')) {
          console.log('Skipped/Already exists:', q, e.message);
        } else {
          console.error('Failed:', q, e.message);
        }
      }
    }
  } catch (e) {
    console.error(e);
  }
  process.exit(0);
})();
