require('dotenv').config();
const { Sequelize } = require('sequelize');

const dbUser = process.env.DB_USER || 'system';
const dbPassword = process.env.DB_PASSWORD || 'admin123';
const dbHost = process.env.DB_HOST || 'localhost';
const dbPort = process.env.DB_PORT || 1521;
const dbService = process.env.DB_SERVICE_NAME || 'XEPDB1';
const dbWalletPath = process.env.DB_WALLET_PATH;
const dbWalletPassword = process.env.DB_WALLET_PASSWORD;

const dialectOptions = {};

if (dbWalletPath) {
  dialectOptions.connectString = dbService;
  dialectOptions.configDir = dbWalletPath;
  dialectOptions.walletLocation = dbWalletPath;
  if (dbWalletPassword) {
    dialectOptions.walletPassword = dbWalletPassword;
  }
} else {
  if (dbService.trim().startsWith('(')) {
    dialectOptions.connectString = dbService;
  } else {
    dialectOptions.connectString = `${dbHost}:${dbPort}/${dbService}`;
  }
}

const sequelize = new Sequelize({
  dialect: 'oracle',
  username: dbUser,
  password: dbPassword,
  dialectOptions,
  logging: false
});

(async () => {
  try {
    await sequelize.authenticate();
    const queries = [
      'ALTER TABLE "products" ADD "reservedQuantity" NUMBER(10) DEFAULT 0',
      'ALTER TABLE "products" ADD "lowStockThreshold" NUMBER(10) DEFAULT 5',
      'ALTER TABLE "products" ADD "images" BLOB',
      'ALTER TABLE "orders" ADD "history" BLOB',
      'ALTER TABLE "orders" ADD "internalNotes" CLOB',
      'ALTER TABLE "inquiries" ADD "leadNotes" CLOB',
      'ALTER TABLE "inquiries" ADD "assignedAdmin" VARCHAR2(255) DEFAULT \'Unassigned\'',
      'ALTER TABLE "inquiries" ADD "history" BLOB',
      'ALTER TABLE "products" ADD "customGiftTagEnabled" NUMBER(1) DEFAULT 1',
      'ALTER TABLE "products" ADD "addonsEnabled" NUMBER(1) DEFAULT 1',
      'ALTER TABLE "products" ADD "customizationText" CLOB',
      'ALTER TABLE "products" ADD "deliveryInfoText" CLOB',
      'ALTER TABLE "settings" MODIFY "value" NULL',
      'CREATE TABLE "testimonials" ("id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR2(255) NOT NULL, "quote" CLOB NOT NULL, "rating" NUMBER(2) DEFAULT 5, "event" VARCHAR2(255) DEFAULT \'\', "isActive" CHAR(1) DEFAULT \'1\', "createdAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL)'
    ];
    for (let q of queries) {
      try {
        await sequelize.query(q);
        console.log('Success:', q);
      } catch (e) {
        if (e.message.includes('ORA-01430') || e.message.includes('ORA-00942') || e.message.includes('ORA-00955')) {
          console.log('Skipped/Already exists:', q, e.message);
        } else {
          console.error('Failed:', q, e.message);
        }
      }
    }
  } catch (e) {
    console.error(e);
  }
  process.exit(0);
})();
